// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ConsoleInteraction console interaction
// swagger:model ConsoleInteraction
type ConsoleInteraction struct {

	// exhibit Id
	// Required: true
	ExhibitID *string `json:"exhibitId"`

	// interaction
	Interaction string `json:"interaction,omitempty"`

	// token Id
	// Required: true
	TokenID *string `json:"tokenId"`
}

// Validate validates this console interaction
func (m *ConsoleInteraction) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateExhibitID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTokenID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ConsoleInteraction) validateExhibitID(formats strfmt.Registry) error {

	if err := validate.Required("exhibitId", "body", m.ExhibitID); err != nil {
		return err
	}

	return nil
}

func (m *ConsoleInteraction) validateTokenID(formats strfmt.Registry) error {

	if err := validate.Required("tokenId", "body", m.TokenID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ConsoleInteraction) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConsoleInteraction) UnmarshalBinary(b []byte) error {
	var res ConsoleInteraction
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
