// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetAvatarForTokenIDHandlerFunc turns a function with the right signature into a get avatar for token ID handler
type GetAvatarForTokenIDHandlerFunc func(GetAvatarForTokenIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAvatarForTokenIDHandlerFunc) Handle(params GetAvatarForTokenIDParams) middleware.Responder {
	return fn(params)
}

// GetAvatarForTokenIDHandler interface for that can handle valid get avatar for token ID params
type GetAvatarForTokenIDHandler interface {
	Handle(GetAvatarForTokenIDParams) middleware.Responder
}

// NewGetAvatarForTokenID creates a new http.Handler for the get avatar for token ID operation
func NewGetAvatarForTokenID(ctx *middleware.Context, handler GetAvatarForTokenIDHandler) *GetAvatarForTokenID {
	return &GetAvatarForTokenID{Context: ctx, Handler: handler}
}

/*GetAvatarForTokenID swagger:route GET /userdata/v1/avatar/{tokenID} getAvatarForTokenId

Get the Avatar associated with the tokenID

*/
type GetAvatarForTokenID struct {
	Context *middleware.Context
	Handler GetAvatarForTokenIDHandler
}

func (o *GetAvatarForTokenID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetAvatarForTokenIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
