// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetStatusByTokenIDParams creates a new GetStatusByTokenIDParams object
// with the default values initialized.
func NewGetStatusByTokenIDParams() GetStatusByTokenIDParams {

	var (
		// initialize parameters with default values

		limitDefault = int32(100)
	)

	return GetStatusByTokenIDParams{
		Limit: &limitDefault,
	}
}

// GetStatusByTokenIDParams contains all the bound params for the get status by token ID operation
// typically these are obtained from a http.Request
//
// swagger:parameters getStatusByTokenID
type GetStatusByTokenIDParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Only return data up to this limit
	  In: query
	  Default: 100
	*/
	Limit *int32
	/*The unique tokenID of the User
	  Required: true
	  In: path
	*/
	TokenID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetStatusByTokenIDParams() beforehand.
func (o *GetStatusByTokenIDParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qLimit, qhkLimit, _ := qs.GetOK("limit")
	if err := o.bindLimit(qLimit, qhkLimit, route.Formats); err != nil {
		res = append(res, err)
	}

	rTokenID, rhkTokenID, _ := route.Params.GetOK("tokenID")
	if err := o.bindTokenID(rTokenID, rhkTokenID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindLimit binds and validates parameter Limit from query.
func (o *GetStatusByTokenIDParams) bindLimit(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewGetStatusByTokenIDParams()
		return nil
	}

	value, err := swag.ConvertInt32(raw)
	if err != nil {
		return errors.InvalidType("limit", "query", "int32", raw)
	}
	o.Limit = &value

	return nil
}

// bindTokenID binds and validates parameter TokenID from path.
func (o *GetStatusByTokenIDParams) bindTokenID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.TokenID = raw

	return nil
}
