// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	models "github.com/artprocessors/nsm-microservice-golang-userdata/restapi/models"
)

// NewPostInteractionParams creates a new PostInteractionParams object
// no default values defined in spec.
func NewPostInteractionParams() PostInteractionParams {

	return PostInteractionParams{}
}

// PostInteractionParams contains all the bound params for the post interaction operation
// typically these are obtained from a http.Request
//
// swagger:parameters postInteraction
type PostInteractionParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: body
	*/
	Interaction *models.ConsoleInteraction
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostInteractionParams() beforehand.
func (o *PostInteractionParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.ConsoleInteraction
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("interaction", "body"))
			} else {
				res = append(res, errors.NewParseError("interaction", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Interaction = &body
			}
		}
	} else {
		res = append(res, errors.Required("interaction", "body"))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
