// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostInteractionHandlerFunc turns a function with the right signature into a post interaction handler
type PostInteractionHandlerFunc func(PostInteractionParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostInteractionHandlerFunc) Handle(params PostInteractionParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostInteractionHandler interface for that can handle valid post interaction params
type PostInteractionHandler interface {
	Handle(PostInteractionParams, interface{}) middleware.Responder
}

// NewPostInteraction creates a new http.Handler for the post interaction operation
func NewPostInteraction(ctx *middleware.Context, handler PostInteractionHandler) *PostInteraction {
	return &PostInteraction{Context: ctx, Handler: handler}
}

/*PostInteraction swagger:route POST /userdata/v1/console/interactions postInteraction

PostInteraction for tokenId

*/
type PostInteraction struct {
	Context *middleware.Context
	Handler PostInteractionHandler
}

func (o *PostInteraction) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostInteractionParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
