// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"
	"strconv"

	errors "github.com/go-openapi/errors"
	middleware "github.com/go-openapi/runtime/middleware"
	strfmt "github.com/go-openapi/strfmt"
	swag "github.com/go-openapi/swag"

	models "github.com/artprocessors/nsm-microservice-golang-userdata/restapi/models"
)

// PostInteractionsHandlerFunc turns a function with the right signature into a post interactions handler
type PostInteractionsHandlerFunc func(PostInteractionsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostInteractionsHandlerFunc) Handle(params PostInteractionsParams) middleware.Responder {
	return fn(params)
}

// PostInteractionsHandler interface for that can handle valid post interactions params
type PostInteractionsHandler interface {
	Handle(PostInteractionsParams) middleware.Responder
}

// NewPostInteractions creates a new http.Handler for the post interactions operation
func NewPostInteractions(ctx *middleware.Context, handler PostInteractionsHandler) *PostInteractions {
	return &PostInteractions{Context: ctx, Handler: handler}
}

/*PostInteractions swagger:route POST /userdata/v1/interactions/{exhibitID}/{tokenID} postInteractions

Store the interaction data for the exhibitID and tokenID

*/
type PostInteractions struct {
	Context *middleware.Context
	Handler PostInteractionsHandler
}

func (o *PostInteractions) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostInteractionsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PostInteractionsBody post interactions body
// swagger:model PostInteractionsBody
type PostInteractionsBody struct {

	// interactions
	Interactions []*models.Interaction `json:"interactions"`
}

// Validate validates this post interactions body
func (o *PostInteractionsBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateInteractions(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostInteractionsBody) validateInteractions(formats strfmt.Registry) error {

	if swag.IsZero(o.Interactions) { // not required
		return nil
	}

	for i := 0; i < len(o.Interactions); i++ {
		if swag.IsZero(o.Interactions[i]) { // not required
			continue
		}

		if o.Interactions[i] != nil {
			if err := o.Interactions[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("interactions" + "." + "interactions" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *PostInteractionsBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostInteractionsBody) UnmarshalBinary(b []byte) error {
	var res PostInteractionsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
