// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/artprocessors/nsm-microservice-golang-userdata/restapi/models"
)

// PostAvatarForTokenIDCreatedCode is the HTTP code returned for type PostAvatarForTokenIDCreated
const PostAvatarForTokenIDCreatedCode int = 201

/*PostAvatarForTokenIDCreated Accepted

swagger:response postAvatarForTokenIdCreated
*/
type PostAvatarForTokenIDCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Avatar `json:"body,omitempty"`
}

// NewPostAvatarForTokenIDCreated creates PostAvatarForTokenIDCreated with default headers values
func NewPostAvatarForTokenIDCreated() *PostAvatarForTokenIDCreated {

	return &PostAvatarForTokenIDCreated{}
}

// WithPayload adds the payload to the post avatar for token Id created response
func (o *PostAvatarForTokenIDCreated) WithPayload(payload *models.Avatar) *PostAvatarForTokenIDCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post avatar for token Id created response
func (o *PostAvatarForTokenIDCreated) SetPayload(payload *models.Avatar) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAvatarForTokenIDCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostAvatarForTokenIDInternalServerErrorCode is the HTTP code returned for type PostAvatarForTokenIDInternalServerError
const PostAvatarForTokenIDInternalServerErrorCode int = 500

/*PostAvatarForTokenIDInternalServerError Internal Server Error

swagger:response postAvatarForTokenIdInternalServerError
*/
type PostAvatarForTokenIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewPostAvatarForTokenIDInternalServerError creates PostAvatarForTokenIDInternalServerError with default headers values
func NewPostAvatarForTokenIDInternalServerError() *PostAvatarForTokenIDInternalServerError {

	return &PostAvatarForTokenIDInternalServerError{}
}

// WithPayload adds the payload to the post avatar for token Id internal server error response
func (o *PostAvatarForTokenIDInternalServerError) WithPayload(payload *models.APIError) *PostAvatarForTokenIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post avatar for token Id internal server error response
func (o *PostAvatarForTokenIDInternalServerError) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAvatarForTokenIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
