// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostInteractionsParams creates a new PostInteractionsParams object
// no default values defined in spec.
func NewPostInteractionsParams() PostInteractionsParams {

	return PostInteractionsParams{}
}

// PostInteractionsParams contains all the bound params for the post interactions operation
// typically these are obtained from a http.Request
//
// swagger:parameters postInteractions
type PostInteractionsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The unique and static ID of the exhibit
	  Required: true
	  In: path
	*/
	ExhibitID string
	/*The interaction data
	  Required: true
	  In: body
	*/
	Interactions PostInteractionsBody
	/*The unique tokenID of the user
	  Required: true
	  In: path
	*/
	TokenID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostInteractionsParams() beforehand.
func (o *PostInteractionsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rExhibitID, rhkExhibitID, _ := route.Params.GetOK("exhibitID")
	if err := o.bindExhibitID(rExhibitID, rhkExhibitID, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body PostInteractionsBody
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("interactions", "body"))
			} else {
				res = append(res, errors.NewParseError("interactions", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Interactions = body
			}
		}
	} else {
		res = append(res, errors.Required("interactions", "body"))
	}
	rTokenID, rhkTokenID, _ := route.Params.GetOK("tokenID")
	if err := o.bindTokenID(rTokenID, rhkTokenID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindExhibitID binds and validates parameter ExhibitID from path.
func (o *PostInteractionsParams) bindExhibitID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.ExhibitID = raw

	return nil
}

// bindTokenID binds and validates parameter TokenID from path.
func (o *PostInteractionsParams) bindTokenID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.TokenID = raw

	return nil
}
