// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/artprocessors/nsm-microservice-golang-userdata/restapi/models"
)

// PostInteractionOKCode is the HTTP code returned for type PostInteractionOK
const PostInteractionOKCode int = 200

/*PostInteractionOK Ok

swagger:response postInteractionOK
*/
type PostInteractionOK struct {

	/*
	  In: Body
	*/
	Payload *models.ConsoleInteraction `json:"body,omitempty"`
}

// NewPostInteractionOK creates PostInteractionOK with default headers values
func NewPostInteractionOK() *PostInteractionOK {

	return &PostInteractionOK{}
}

// WithPayload adds the payload to the post interaction o k response
func (o *PostInteractionOK) WithPayload(payload *models.ConsoleInteraction) *PostInteractionOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post interaction o k response
func (o *PostInteractionOK) SetPayload(payload *models.ConsoleInteraction) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostInteractionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostInteractionCreatedCode is the HTTP code returned for type PostInteractionCreated
const PostInteractionCreatedCode int = 201

/*PostInteractionCreated Created

swagger:response postInteractionCreated
*/
type PostInteractionCreated struct {

	/*
	  In: Body
	*/
	Payload *models.ConsoleInteraction `json:"body,omitempty"`
}

// NewPostInteractionCreated creates PostInteractionCreated with default headers values
func NewPostInteractionCreated() *PostInteractionCreated {

	return &PostInteractionCreated{}
}

// WithPayload adds the payload to the post interaction created response
func (o *PostInteractionCreated) WithPayload(payload *models.ConsoleInteraction) *PostInteractionCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post interaction created response
func (o *PostInteractionCreated) SetPayload(payload *models.ConsoleInteraction) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostInteractionCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostInteractionBadRequestCode is the HTTP code returned for type PostInteractionBadRequest
const PostInteractionBadRequestCode int = 400

/*PostInteractionBadRequest Invalid request

swagger:response postInteractionBadRequest
*/
type PostInteractionBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewPostInteractionBadRequest creates PostInteractionBadRequest with default headers values
func NewPostInteractionBadRequest() *PostInteractionBadRequest {

	return &PostInteractionBadRequest{}
}

// WithPayload adds the payload to the post interaction bad request response
func (o *PostInteractionBadRequest) WithPayload(payload *models.APIError) *PostInteractionBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post interaction bad request response
func (o *PostInteractionBadRequest) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostInteractionBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostInteractionNotFoundCode is the HTTP code returned for type PostInteractionNotFound
const PostInteractionNotFoundCode int = 404

/*PostInteractionNotFound Not found

swagger:response postInteractionNotFound
*/
type PostInteractionNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewPostInteractionNotFound creates PostInteractionNotFound with default headers values
func NewPostInteractionNotFound() *PostInteractionNotFound {

	return &PostInteractionNotFound{}
}

// WithPayload adds the payload to the post interaction not found response
func (o *PostInteractionNotFound) WithPayload(payload *models.APIError) *PostInteractionNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post interaction not found response
func (o *PostInteractionNotFound) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostInteractionNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostInteractionInternalServerErrorCode is the HTTP code returned for type PostInteractionInternalServerError
const PostInteractionInternalServerErrorCode int = 500

/*PostInteractionInternalServerError Internal server error

swagger:response postInteractionInternalServerError
*/
type PostInteractionInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewPostInteractionInternalServerError creates PostInteractionInternalServerError with default headers values
func NewPostInteractionInternalServerError() *PostInteractionInternalServerError {

	return &PostInteractionInternalServerError{}
}

// WithPayload adds the payload to the post interaction internal server error response
func (o *PostInteractionInternalServerError) WithPayload(payload *models.APIError) *PostInteractionInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post interaction internal server error response
func (o *PostInteractionInternalServerError) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostInteractionInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
