// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/artprocessors/nsm-microservice-golang-userdata/restapi/models"
)

// PostInteractionsOKCode is the HTTP code returned for type PostInteractionsOK
const PostInteractionsOKCode int = 200

/*PostInteractionsOK Ok

swagger:response postInteractionsOK
*/
type PostInteractionsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Interaction `json:"body,omitempty"`
}

// NewPostInteractionsOK creates PostInteractionsOK with default headers values
func NewPostInteractionsOK() *PostInteractionsOK {

	return &PostInteractionsOK{}
}

// WithPayload adds the payload to the post interactions o k response
func (o *PostInteractionsOK) WithPayload(payload []*models.Interaction) *PostInteractionsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post interactions o k response
func (o *PostInteractionsOK) SetPayload(payload []*models.Interaction) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostInteractionsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Interaction, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// PostInteractionsBadRequestCode is the HTTP code returned for type PostInteractionsBadRequest
const PostInteractionsBadRequestCode int = 400

/*PostInteractionsBadRequest Invalid request

swagger:response postInteractionsBadRequest
*/
type PostInteractionsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewPostInteractionsBadRequest creates PostInteractionsBadRequest with default headers values
func NewPostInteractionsBadRequest() *PostInteractionsBadRequest {

	return &PostInteractionsBadRequest{}
}

// WithPayload adds the payload to the post interactions bad request response
func (o *PostInteractionsBadRequest) WithPayload(payload *models.APIError) *PostInteractionsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post interactions bad request response
func (o *PostInteractionsBadRequest) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostInteractionsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostInteractionsNotFoundCode is the HTTP code returned for type PostInteractionsNotFound
const PostInteractionsNotFoundCode int = 404

/*PostInteractionsNotFound Not found

swagger:response postInteractionsNotFound
*/
type PostInteractionsNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewPostInteractionsNotFound creates PostInteractionsNotFound with default headers values
func NewPostInteractionsNotFound() *PostInteractionsNotFound {

	return &PostInteractionsNotFound{}
}

// WithPayload adds the payload to the post interactions not found response
func (o *PostInteractionsNotFound) WithPayload(payload *models.APIError) *PostInteractionsNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post interactions not found response
func (o *PostInteractionsNotFound) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostInteractionsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostInteractionsInternalServerErrorCode is the HTTP code returned for type PostInteractionsInternalServerError
const PostInteractionsInternalServerErrorCode int = 500

/*PostInteractionsInternalServerError Internal server error

swagger:response postInteractionsInternalServerError
*/
type PostInteractionsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewPostInteractionsInternalServerError creates PostInteractionsInternalServerError with default headers values
func NewPostInteractionsInternalServerError() *PostInteractionsInternalServerError {

	return &PostInteractionsInternalServerError{}
}

// WithPayload adds the payload to the post interactions internal server error response
func (o *PostInteractionsInternalServerError) WithPayload(payload *models.APIError) *PostInteractionsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post interactions internal server error response
func (o *PostInteractionsInternalServerError) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostInteractionsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
