// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi User Data Service
User Data service for storing and querying user interactions.


    Schemes:
      http
    Host: localhost:8080
    BasePath: /
    Version: 1.0.1
    License: Stephen Graham
    Contact: <stephram@gmail.com>

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
