// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi User Data Service
User Data service for storing and querying user interactions.


    Schemes:
      http
    Host: localhost:8080
    BasePath: /
    Version: 1.0.0
    License: Art Processors Pty. Ltd. https://www.artprocessors.net/licensing
    Contact: <support@artprocessors.net>

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
